const menuList = [
  {
    icon: 'mdi mdi-security',
    name: 'ສິດທີການໃຊ້ງານ',
    llname: 'ສິດທີການໃຊ້ງານ',
    path: '/admin/authority',
  },
  {
    icon: 'mdi mdi-account-multiple',
    name: 'ກຸ່ມຜູ້ໃຊ້ງານ',
    llname: 'ກຸ່ມຜູ້ໃຊ້ງານ',
    path: '/admin/group',
  },
  {
    icon: 'mdi-account',
    name: 'ຜູ້ໃຊ້ງານ',
    llname: 'ຜູ້ໃຊ້ງານ',
    path: '/admin/user',
  },
  {
    icon: 'mdi mdi-lifebuoy',
    name: 'ຄູ່ມືການນຳໃຊ້',
    llname: 'ຄູ່ມືການນຳໃຊ້',
    path: '/admin/tupathrial',
  },
  {
    icon: 'mdi mdi-chevron-triple-up',
    name: 'ຟັງຊັ່ນເສີມ',
    llname: 'ຟັງຊັ່ນເສີມ',
    path: '/admin/authoritysss',
  },
  {
    icon: 'mdi-currency-usd-off',
    name: 'ຈັດການອັດຕາແລກປ່ຽນ',
    llname: 'ຈັດການອັດຕາແລກປ່ຽນ',
    path: '/admin/currency',
  },
  {
    icon: 'mdi mdi-office-building',
    name: 'ຜັງບັນຊີ',
    llname: 'ຜັງບັນຊີ',
    path: '/admin/chartAccount',
  },
  {
    icon: 'mdi mdi-cash-multiple',
    name: 'ຈັດການ ປະເພດຊຳລະ',
    llname: 'ຈັດການ ປະເພດຊຳລະ',
    path: '/admin/payment',
  },
  {
    icon: 'mdi-receipt-text-arrow-right-outline',
    name: 'ບັນຊີ ລາຍຈ່າຍ',
    llname: 'ບັນຊີ ລາຍຈ່າຍ',
    path: '/admin/ap',
  },
  {
    icon: 'mdi-receipt-text-arrow-left-outline',
    name: 'ບັນຊີ ລາຍຮັບ',
    llname: 'ບັນຊີ ລາຍຮັບ',
    path: '/admin/ar',
  },
  {
    icon: 'mdi mdi-source-branch',
    name: 'ຈັດການຮ້ານຄ້າ',
    llname: 'ຈັດການຮ້ານຄ້າ',
    path: '/admin/company',
  },
  {
    icon: 'mdi mdi-network-pos',
    name: 'ຈັດການສາຂາ',
    llname: 'ຈັດການສາຂາ',
    path: '/admin/terminal',
  },
  {
    icon: 'mdi mdi-warehouse',
    name: 'ຈັດການສາງສິນຄ້າ',
    llname: 'ຈັດການສາງສິນຄ້າ',
    path: '/admin/location',
  },
  {
    icon: 'mdi mdi-speedometer-slow',
    name: 'ສິນຄ້າໃກ້ໝົດ',
    llname: 'ສິນຄ້າໃກ້ໝົດ',
    path: '/admin/minspathck',
  },
  {
    icon: 'mdi mdi-transfer',
    name: 'ໂອນສາງ',
    llname: 'ໂອນສາງ',
    path: '/admin/transfer',
  },
  {
    icon: 'mdi-view-list',
    name: 'ຈັດການໝວດສິນຄ້າ',
    llname: 'ຈັດການໝວດສິນຄ້າ',
    path: '/admin/category',
  },
  {
    icon: 'mdi-barcode',
    name: 'ລາຍການສິນຄ້າ',
    llname: 'ລາຍການສິນຄ້າ',
    path: '/admin/product/productlist',
  },
  {
    icon: 'mdi mdi-bottle-wine',
    name: 'ຫົວໜ່ວຍສິນຄ້າ',
    llname: 'ຫົວໜ່ວຍສິນຄ້າ',
    path: '/admin/unit',
  },
  {
    icon: 'mdi-view-list',
    name: 'POS',
    llname: 'POS',
    path: '/pos',
  },
  {
    icon: 'mdi-receipt-text-arrow-right',
    name: 'ໃບສະເຫນີລາຄາ',
    llname: 'ໃບສະເຫນີລາຄາ',
    path: '/admin/quotationList',
  },
  {
    icon: 'mdi-receipt-text-check-outline',
    name: 'ລາຍການບິນຂາຍ POS',
    llname: 'ລາຍການບິນຂາຍ POS',
    path: '/admin/ordersFromPos',
  },
  {
    icon: 'mdi-receipt-text-check-outline',
    name: 'ລາຍການບິນຂາຍ Online',
    llname: 'ລາຍການບິນຂາຍ Online',
    path: '/admin/ordersFromPosOnline',
  },
  {
    icon: 'mdi-receipt-text-check-outline',
    name: 'ຕິດຕາມ COD',
    llname: 'ຕິດຕາມ COD',
    path: '/admin/ordersFromPosOnlineCOD',
  },
  {
    icon: 'mdi-receipt-text-remove-outline',
    name: 'ຍົກເລີກ - ສົ່ງຄືນ',
    llname: 'ຍົກເລີກ - ສົ່ງຄືນ',
    path: '/admin/ordersFromPosCancel',
  },
  {
    icon: 'mdi mdi-shopping',
    name: 'ຈັດການອໍເດີ',
    llname: 'ຈັດການອໍເດີ',
    path: '/admin/orders',
  },
  {
    icon: 'mdi mdi-wardrobe',
    name: 'ເຄື່ອງເຂົ້າສາງ',
    llname: 'ເຄື່ອງເຂົ້າສາງ',
    path: '/admin/ordersIn',
  },
  {
    icon: 'mdi mdi-receipt-text-check',
    name: 'ອອກບິນຮັບເຄື່ອງ',
    llname: 'ອອກບິນຮັບເຄື່ອງ',
    path: '/admin/ordersOut',
  },
  {
    icon: 'mdi mdi-notebook-multiple',
    name: 'ອໍເດີທັງໝົດ',
    llname: 'ອໍເດີທັງໝົດ',
    path: '/admin/ordersAll',
  },
  {
    icon: 'mdi-spathre-marker-outline',
    name: 'Vendor',
    llname: 'Vendor',
    path: '/admin/vendor',
  },
  {
    icon: 'mdi mdi-patholtip-account',
    name: 'ລູກຄ້າ',
    llname: 'ລູກຄ້າ',
    path: '/admin/client',
  },
  {
    icon: 'mdi mdi-file-chart',
    name: 'ຄົ້ນຫາຍຍອດຂາຍ ຕາມຜູ້ໃຊ້',
    llname: 'ຄົ້ນຫາຍຍອດຂາຍ ຕາມຜູ້ໃຊ້',
    path: '/admin/saleReportDetailByUser',
  },
  {
    icon: 'mdi mdi-file-chart',
    name: 'ຄົ້ນຫາຍອດຂາຍ ຕາມລູກຄ້າ',
    llname: 'ຄົ້ນຫາຍອດຂາຍ ຕາມລູກຄ້າ',
    path: '/admin/saleReportDetailByCuspathmer',
  },
  {
    icon: 'mdi mdi-file-chart',
    name: 'ຄົ້ນຫາຍອດຂາຍ ຕາມສິນຄ້າ',
    llname: 'ຄົ້ນຫາຍອດຂາຍ ຕາມສິນຄ້າ',
    path: '/admin/saleReportDetailByProduct',
  },
]

module.exports = {
  menuList
}